# Generated by Django 3.1.7 on 2021-02-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210228_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='header',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
