# Generated by Django 3.1.7 on 2021-02-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210228_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='merchant_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='secret_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
